#!/bin/bash
#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2018 Intel Corporation
#
# Authors: Fengguang Wu <fengguang.wu@intel.com>
#          Yao Yuan <yuan.yao@intel.com>
#

commit=$(git rev-list -1 HEAD)

diff=$(git diff HEAD)
if [[ -n "$diff" ]]; then
    diff_sum=+$(echo "$diff" | md5sum | cut -f1 -d ' ')
    diff_stat=$(echo "$diff" | diffstat | sed 's/$/\\n\\/')
    diff_stat="\n\\"$'\n'"${diff_stat::-3}"
else
    diff_sum=
    diff_stat=
fi

cat > version.h <<EOF
#ifndef _AEP_VERSION_H_
#define _AEP_VERSION_H_

// auto generated by get_version.sh

#define VERSION_TIME		"$(date +'%F %T')"
#define VERSION_COMMIT		"$commit"
#define VERSION_DIFFSUM		"$diff_sum"
#define VERSION_DIFFSTAT	"$diff_stat"

void print_version()
{
  printf("%s\n", VERSION_TIME " " VERSION_COMMIT VERSION_DIFFSUM VERSION_DIFFSTAT);
}

#endif
EOF
