#!/bin/bash

script_path=$(realpath $0)
tests_dir=$(dirname $script_path)
project_dir=$(dirname $tests_dir)
cd "$tests_dir" || exit

# task-refs params on thp=never
setup_migration_thp_never()
{
	loop=10
	interval=$(echo "0.1 * $mem_gb" | bc)
}

setup_migration_thp_always()
{
	loop=20
	interval=$(echo "0.01 * $mem_gb" | bc)
}

setup_sys()
{
	echo $thp > /sys/kernel/mm/transparent_hugepage/enabled
	echo 0 > /proc/sys/kernel/numa_balancing

	lsmod | grep -q kvm_ept_idle || insmod $tests_dir/kvm-ept-idle.ko
}

run_migrations()
{
	local what=$1
	local i

	for i in $(seq 30)
	do
		sleep 1
		grep -q "Threads started" $log_file && break
	done

        task_refs_cmd=(
                $project_dir/task-refs
                -i $interval
                -d $dram_percent
                -m $what
                -p $sysbench_pid
        )

	for i in 2 1 1
	do
		sleep $i
		echo
		echo "${task_refs_cmd[@]}"
		/usr/bin/time -v "${task_refs_cmd[@]}"
		cat refs-count-$sysbench_pid
	done
}

run_test()
{
	local suffix=$1
	local mempolicy="$2"

	sysbench_cmd=(
		#numactl
		#--interleave=all

		# perf stat
		# -e dTLB-load-misses,iTLB-load-misses
		# --

		sysbench
		--time=$time
		memory
		--memory-block-size=$memory_block_size
		--memory-total-size=1T
		--memory-oper=$memory_oper
		--memory-access-mode=rnd
		--rand-type=$rand_type
		run
	)

	log_file=$log_dir/$memory_oper-$rand_type-$thp.$suffix
	exec > $log_file 2>&1

	echo numactl $mempolicy "${sysbench_cmd[@]}"
	numactl $mempolicy "${sysbench_cmd[@]}" &

	local sysbench_pid=$!

	trap "kill $sysbench_pid; exit" SIGINT SIGQUIT

	if [[ $suffix == 'h' ]]; then
		run_migrations hot
	elif [[ $suffix == 'c' ]]; then
		run_migrations cold
	elif [[ $suffix == 'b' ]]; then
		run_migrations both
	else
		sleep 2
	fi

	grep active_anon /sys/devices/system/node/node*/vmstat

	wait
}

run_tests()
{
	setup_sys
	setup_migration_thp_$thp

	run_test 0 "-m0"
	run_test 1 "-m1"
	# run_test i "-i all"
	run_test h "-m1"
	# run_test c "-m0"
}

log_dir=$(basename $0)-$(date +'%Y%m%d_%H%M%S')
mkdir -p $tests_dir/$log_dir
cp -a $script_path $tests_dir/$log_dir/
echo vimdiff $tests_dir/$log_dir/*.?

thp=never
thp=always
mem_gb=2
dram_percent=25

# sysbench params
time=10
rand_type=pareto
memory_oper=read
memory_block_size=${mem_gb}G

run_tests
# memory_oper=write
# run_tests
# this requires adjusting interval
# thp=always
# run_tests
# memory_oper=read
# run_tests
#rand_type=zipfian
#run_tests
